# =============================================================================
# dbt Profiles - Conexi칩n al Spark Thrift Server
# =============================================================================
# Este archivo configura la conexi칩n de dbt al Spark Thrift Server.
# 
# Ubicaci칩n: debe estar en dbt_gold/profiles.yml para que Airflow lo encuentre
# cuando ejecute dbt desde dentro del contenedor.
#
# Para uso local (desde Windows), el profiles.yml est치 en:
#   C:\Users\lopez\.dbt\profiles.yml
#
# Para uso desde contenedor (Airflow), este archivo se monta en:
#   /app/dbt_gold/profiles.yml
# =============================================================================

dbt_gold:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: localhost  # Desde dentro del contenedor spark-thrift
      port: 10000
      schema: default
      threads: 1