# Conexión de dbt al Spark Thrift Server
# Desde Airflow (contenedor): este archivo se monta en /app/dbt_gold/profiles.yml
# Desde Windows (local): C:\Users\lopez\.dbt\profiles.yml

dbt_gold:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: localhost  # Desde dentro del contenedor spark-thrift
      port: 10000
      schema: default
      threads: 1